# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1449270588);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1449270708);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1449274500);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1449270468);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1449263571);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "/home/amid/Escritorio");
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.search.countryCode", "AR");
user_pref("browser.search.region", "AR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20151103235259");
user_pref("browser.slowStartup.averageTime", 7524);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 9);
user_pref("extensions.blocklist.pingCountVersion", 9);
user_pref("extensions.bootstrappedAddons", "{\"langpack-es-MX@iceweasel.mozilla.org\":{\"version\":\"38.4.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-es-MX@iceweasel.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-es-CL@iceweasel.mozilla.org\":{\"version\":\"38.4.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-es-CL@iceweasel.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-es-AR@iceweasel.mozilla.org\":{\"version\":\"38.4.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-es-AR@iceweasel.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-es-ES@iceweasel.mozilla.org\":{\"version\":\"38.4.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-es-ES@iceweasel.mozilla.org.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.4.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1449270590);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "38.4.0");
user_pref("extensions.lastPlatformVersion", "38.4.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-es-MX@iceweasel.mozilla.org\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/langpack-es-MX@iceweasel.mozilla.org.xpi\",\"e\":true,\"v\":\"38.4.0\",\"st\":1446597075000},\"langpack-es-CL@iceweasel.mozilla.org\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/langpack-es-CL@iceweasel.mozilla.org.xpi\",\"e\":true,\"v\":\"38.4.0\",\"st\":1446597069000},\"langpack-es-AR@iceweasel.mozilla.org\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/langpack-es-AR@iceweasel.mozilla.org.xpi\",\"e\":true,\"v\":\"38.4.0\",\"st\":1446597065000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.4.0\",\"st\":1448288831000,\"mt\":1446596930000},\"langpack-es-ES@iceweasel.mozilla.org\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/langpack-es-ES@iceweasel.mozilla.org.xpi\",\"e\":true,\"v\":\"38.4.0\",\"st\":1446597072000}}}");
user_pref("gecko.buildID", "20151103235259");
user_pref("gecko.mstone", "38.4.0");
user_pref("idle.lastDailyNotification", 1449270653);
user_pref("media.gmp-manager.buildID", "20151103235259");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1449184243);
user_pref("places.history.expiration.transient_current_max_pages", 51679);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("spellchecker.dictionary", "es-CO");
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1448378760);
user_pref("toolkit.startup.last_success", 1449657435);
user_pref("toolkit.telemetry.previousBuildID", "20151103235259");
