/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : LP.H
**     Project   : controlserie
**     Processor : MC9S08SH8CPJ
**     Component : Capture
**     Version   : Component 02.211, Driver 01.27, CPU db: 3.00.062
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 12/15/2015, 6:40 AM
**     Abstract  :
**         This bean "Capture" simply implements the capture function
**         of timer. The counter counts the same way as in free run mode. On
**         the selected edge of the input signal (on the input pin), the current
**         content of the counter register is written into the capture
**         register and the OnCapture event is called.
**     Settings  :
**             Timer capture encapsulation : Capture
**
**         Timer
**             Timer                   : TPM2
**             Counter shared          : Yes
**
**         High speed mode
**             Prescaler               : divide-by-64
**           Maximal time for capture register
**             Xtal ticks              : 32768
**             microseconds            : 1048576
**             milliseconds            : 1049
**             seconds                 : 1
**             seconds (real)          : 1.048576
**             Hz                      : 1
**           One tick of timer is
**             microseconds            : 16
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Capture                : TPM2C0V   [$0066]
**              Counter                : TPM2CNT   [$0061]
**              Mode                   : TPM2SC    [$0060]
**              Run                    : TPM2SC    [$0060]
**              Prescaler              : TPM2SC    [$0060]
**
**         Used input pin              : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       19            |  PTA1_PIA1_TPM2CH0_ADP1_ACMPMINUS
**             ----------------------------------------------------
**
**         Port name                   : PTA
**         Bit number (in port)        : 1
**         Bit mask of the port        : $0002
**
**         Signal edge/level           : rising
**         Priority                    : 
**         Pull option                 : off
**
**     Contents  :
**         Reset           - byte LP_Reset(void);
**         GetCaptureValue - byte LP_GetCaptureValue(LP_TCapturedValue *Value);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __LP
#define __LP

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"

/* MODULE LP. */

#include "Cpu.h"

/* PUBLISHED CONSTANTS */
#define LP_PRESCALER_VALUE           0x40U /* Prescaler value of the timer in high speed mode */
#define LP_COUNTER_INPUT_CLOCK_HZ    0xF424LU /* Initial counter input clock frequency [Hz] */
#define LP_TIMER_INPUT_CLOCK         0x003D0900LU /* Deprecated, Initial timer input clock frequency [Hz] */
#define LP_PRESCALER_VALUE_HIGH      0x40U /* Prescaler value of the timer in high speed mode */
#define LP_COUNTER_INPUT_CLOCK_HZ_HIGH 0xF424LU /* Counter input clock frequency in high speed mode [Hz] */
#define LP_TIMER_INPUT_CLOCK_HIGH    0x003D0900LU /* Deprecated, Timer input clock frequency in high speed mode[Hz] */

#ifndef __BWUserType_LP_TCapturedValue
#define __BWUserType_LP_TCapturedValue
  #define LP_TCapturedValue word       /* Type of the captured value */
#endif


extern volatile word LP_CntrState;     /* Content of counter */


#define LP_Reset() \
  (LP_CntrState = TPM2CNT , (byte)ERR_OK)
/*
** ===================================================================
**     Method      :  LP_Reset (component Capture)
**
**     Description :
**         This method resets the counter register (see implementation
**         note in <General Info>).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

#define LP_GetCaptureValue(Value) \
  (*(LP_TCapturedValue*)(Value) = (LP_TCapturedValue)(TPM2C0V - LP_CntrState), (byte)ERR_OK)
/*
** ===================================================================
**     Method      :  LP_GetCaptureValue (component Capture)
**
**     Description :
**         This method gets the last value captured by enabled timer.
**         Note: one tick of timer is
**               16 us in high speed mode
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Value           - A pointer to the content of the
**                           capture register
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

void LP_Init(void);
/*
** ===================================================================
**     Method      :  LP_Init (component Capture)
**
**     Description :
**         Initializes the associated peripheral(s) and the bean internal 
**         variables. The method is called automatically as a part of the 
**         application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void LP_Interrupt(void);
/*
** ===================================================================
**     Method      :  Interrupt (component Capture)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes of the bean event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/


/* END LP. */

#endif /* ifndef __LP */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
